### ISSUE TITLE
Keymon not opening in ubuntu 24.04

### ISSUE THREAD

**Issue by aanandharaja** [scottkirkwood/key-mon#106]
Hi
Recently installed ubuntu 24.04LTS installed without any error but not opening when i open it from terminal showing the following error
Traceback (most recent call last):
  File "/usr/bin/key-mon", line 2, in <module>
    import keymon.key_mon as km
  File "/usr/lib/python3/dist-packages/keymon/key_mon.py", line 41, in <module>
    from . import settings
  File "/usr/lib/python3/dist-packages/keymon/settings.py", line 29, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?

**Comment by zirneklitis** [comment]
This is duplicate of #105
