### ISSUE TITLE
Unable to install on Linux Mint 22

### ISSUE THREAD

**Issue by mrmatteastwood** [scottkirkwood/key-mon#109]
Hi! I tried installing key-mon on Linux Mint 22 and this happened:

```
$ pip install key-mon
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

So I looked this up and apparently, one can use a tool called "pipx" to install programs and then it should work. So I did this:

`pipx install key-mon`

When I try to run it, I get the following error:

`Error: Missing xlib, run sudo apt-get install python3-xlib`

I tried installing it, but apparently it's already installed. So ChatGPT suggested I install it in the same sandbox that I used pipx to install key-mon in, so I did that with this command:

`pipx runpip key-mon install python3-xlib`

Then I landed here:

```
$ key-mon
Traceback (most recent call last):
  File "/home/thebrightside/.local/bin/key-mon", line 2, in <module>
    import keymon.key_mon as km
  File "/home/thebrightside/.local/share/pipx/venvs/key-mon/lib/python3.12/site-packages/keymon/key_mon.py", line 39, in <module>
    from . import lazy_pixbuf_creator
  File "/home/thebrightside/.local/share/pipx/venvs/key-mon/lib/python3.12/site-packages/keymon/lazy_pixbuf_creator.py", line 39, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

ChatGPT told me to try installing PyGObject:

```
$ pipx install PyGObject
Fatal error from pip prevented installation. Full pip output in file:
    /home/thebrightside/.local/state/pipx/log/cmd_2024-11-11_18.58.09_pip_errors.log

pip seemed to fail to build package:
    pygobject

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../cairo/meson.build:31:12: ERROR: Dependency "cairo" not found, tried pkgconfig
    error: metadata-generation-failed

Error installing pygobject.

```

So then I installed cairo and a bunch of stuff that ChatGPT suggested:

`sudo apt-get install build-essential libglib2.0-dev libcairo2-dev libgirepository1.0-dev pkg-config`

But then this happened:

```
$ pipx install PyGObject

No apps associated with package pygobject or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

And now I'm back to sqare one, with the externally managed environment hoo-haa. I have no idea where to go from here, and I don't know why all this externally managed environment song and dance is happening in the first place. It was all good and dandy when I was running Linux Mint 21.3, and now after I reformatted my PC, installed LM 22 and then python3, python3.12 and python3.13, it's all messed up.

Any help would be truly greatly appreciated :-) Thanks!

**Comment by Fr-Dae** [comment]
samehere
Lubuntu 24.10

```
dae@dae-gl753vd:~$ pip install key-mon
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by setaur** [comment]
Instruction:
https://github.com/scottkirkwood/key-mon/issues/111#issuecomment-4296996800
